# This workflow runs on all PRs to enforce coding standards and optionally publish to a unique dist tag.
#
# The jobs are:
#   `lint_code`: runs syntax checking and linting.

name: Enforce Coding Standards

on:
  workflow_call:

jobs:
  run_tests:
    name: Lint & Test
    runs-on: [self-hosted, dj-ubuntu-2004-latest, ARM64]
    timeout-minutes: 30

    env:
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Lint the application
        run: npm run lint

      - name: Test the application
        env:
          DATA_CACHING_OFF: true
        run: npm run test -- --runInBand --coverage=true --silent
