name: Dump Event Payload

on:
  push:
    branches: ['test']

jobs:
  dump_payload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump event payload
        run: |
          echo "Event payload:"
          echo "${{ toJson(github.event) }}"
          echo "Event type: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
  ping_servo:
    needs: dump_payload
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test Servo
        env:
          SERVO_TOKEN: ${{ secrets.SERVO_TOKEN }}
          EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: bash scripts/servo-builds/entrypoint.sh